sym16_simple_stock_iLike:
    path:	/iLike/{verbe}
    defaults: {_controller: SYM16SimpleStockBundle:RVCEPremierControleur:iLike }

sym16_simple_stock_mult:
    path:	/produit/{var1}/{var2}
    defaults: {_controller: SYM16SimpleStockBundle:RVCEPremierControleur:produit }

sym16_simple_stock_hexa:
    path:       /hexa/{var1}/{var2}
    defaults: {_controller: SYM16SimpleStockBundle:RVCEPremierControleur:hexa }
    requirements:
        var1:   ^[0-9a-fA-F]*$
        var2:   ^[0-9a-fA-F]*$

sym16_simple_stock_homepage:
    path:    /home/{name}
    defaults: {_controller: SYM16SimpleStockBundle:Default:index }

sym16_simple_stock_racine:
    path:    /racine/{valeur}/{radical}
    defaults: {_controller: SYM16SimpleStockBundle:RVCEPremierControleur:racine }
